{% set name = "empymod" %}
{% set version = "1.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1881ede8dc1c643216367b52f129cbb7e82b4c3906e857553f4fba5585d7991f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  preserve_egg_dir: True

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - numpy
    - python >=3.5
    - scipy >=1.0.0

test:
  imports:
    - empymod
    - empymod.scripts

about:
  home: https://empymod.github.io
  license: "Apache Software"
  license_family: APACHE
  license_file: LICENSE
  summary: "Open-source full 3D electromagnetic modeller for 1D VTI media"
  description: |
    The electromagnetic modeller empymod can model electric or magnetic
    responses due to a three-dimensional electric or magnetic source in a
    layered-earth model with vertical transverse isotropic (VTI) resistivity,
    VTI electric permittivity, and VTI magnetic permeability, from very low
    frequencies (DC) to very high frequencies (GPR). The calculation is carried
    out in the wavenumber-frequency domain, and various Hankel- and
    Fourier-transform methods are included to transform the responses into the
    space-frequency and space-time domains.
  doc_url: https://empymod.readthedocs.io/
  dev_url: https://github.com/empymod/empymod

extra:
  recipe-maintainers:
    - prisae
