{% set name = "empymod" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad5e4d519db0fb4dcfe22a3395e9473c1d57ebd95ac931ec9b3aa50f94ad9d0b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  preserve_egg_dir: true

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - numba
    - numpy
    - python >=3.6
    - scipy >=1.0.0

test:
  imports:
    - empymod
    - empymod.scripts

about:
  home: https://empymod.github.io
  license: Apache License 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open-source full 3D electromagnetic modeller for 1D VTI media
  description: |
    The electromagnetic modeller empymod can model electric or magnetic
    responses due to a three-dimensional electric or magnetic source in a
    layered-earth model with vertical transverse isotropic (VTI) resistivity,
    VTI electric permittivity, and VTI magnetic permeability, from very low
    frequencies (DC) to very high frequencies (GPR). The calculation is carried
    out in the wavenumber-frequency domain, and various Hankel- and
    Fourier-transform methods are included to transform the responses into the
    space-frequency and space-time domains.
  doc_url: https://empymod.readthedocs.io/
  dev_url: https://github.com/empymod/empymod

extra:
  recipe-maintainers:
    - prisae
