{% set name = "empymod" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b42320a8b4cf901cf41b954f5d64d346b7c746d514e2f96284785ba14fe4ba1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - empymod=empymod.__main__:main

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - numba >=0.47
    - python >=3.7
    - scipy >=1.4.0

test:
  imports:
    - empymod
    - empymod.scripts

about:
  home: https://emsig.xyz
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open-source full 3D electromagnetic modeller for 1D VTI media
  description: |
    The electromagnetic modeller empymod can model electric or magnetic
    responses due to a three-dimensional electric or magnetic source in a
    layered-earth model with vertical transverse isotropic (VTI) resistivity,
    VTI electric permittivity, and VTI magnetic permeability, from very low
    frequencies (DC) to very high frequencies (GPR). The calculation is carried
    out in the wavenumber-frequency domain, and various Hankel- and
    Fourier-transform methods are included to transform the responses into the
    space-frequency and space-time domains.
  doc_url: https://empymod.emsig.xyz
  dev_url: https://github.com/emsig/empymod

extra:
  recipe-maintainers:
    - prisae
